// <auto-generated />
namespace Accedia.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AddMenu : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddMenu));
        
        string IMigrationMetadata.Id
        {
            get { return "201602272131288_AddMenu"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
